### ISSUE TITLE
Version 4.26: Test uint128 math, bitwise shift operators and i/o operations fails 

### ISSUE THREAD

**Issue by cboltz** [rabauke/trng4#33] opened 2024-08-20 18:46 UTC
Building 4.26 on openSUSE fails for the s390x architecture with various test failures in the uint128 math, bitwise shift operators and i/o operations  tests.

The detailed error log is (collapsed to keep the ticket readable):

<details>

<summary>detailed log of test failures</summary>

```
[  213s]  3/59 Test  #2: uint128 math ..................................***Failed    0.31 sec
[  213s] Filters: uint128 math
[  213s] 
[  213s] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  213s] test_all is a Catch v2.13.10 host application.
[  213s] Run with -? for options
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 math
[  213s]   arithmetic operators
[  213s]   divide
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:257
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:276: FAILED:
[  213s]   REQUIRE( a / b == y )
[  213s] with expansion:
[  213s]   0 == 2418386594807395926409216
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 math
[  213s]   arithmetic operators
[  213s]   reminder
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:280
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:299: FAILED:
[  213s]   REQUIRE( a % b == y )
[  213s] with expansion:
[  213s]   132621255386376390035750158631128006656
[  213s]   ==
[  213s]   222097224137778231752483148592416765127
[  213s] 
[  213s] ===============================================================================
[  213s] test cases:  1 |  0 passed | 1 failed
[  213s] assertions: 97 | 95 passed | 2 failed
[  213s] 
[  213s] 
[  213s]       Start 11: modulo inverse
[  213s]  4/59 Test  #4: uint128 bitwise shift operators ...............***Failed    0.30 sec
[  213s] Filters: uint128 bitwise shift operators
[  213s] 
[  213s] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  213s] test_all is a Catch v2.13.10 host application.
[  213s] Run with -? for options
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 bitwise shift operators
[  213s]   bitwise shift operators left
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:376
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:398: FAILED:
[  213s]   REQUIRE( (a << b) == c )
[  213s] with expansion:
[  213s]   0 == 9223372036854775808
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 bitwise shift operators
[  213s]   bitwise shift operators right
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:402
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:424: FAILED:
[  213s]   REQUIRE( (a >> b) == c )
[  213s] with expansion:
[  213s]   5148187932181022
[  213s]   ==
[  213s]   56400652756100854782274289354670080
[  213s] 
[  213s] ===============================================================================
[  213s] test cases: 1 | 1 failed
[  213s] assertions: 4 | 2 passed | 2 failed
[  213s] 
[  213s] 
[  213s]  5/59 Test  #6: basic vector operations .......................   Passed    0.20 sec
[  213s]       Start 12: special_functions - float
[  213s]       Start 13: special_functions - double
[  213s]  6/59 Test  #5: uint128 i/o operations ........................***Failed    0.36 sec
[  213s] Filters: uint128 i/o operations
[  213s] 
[  213s] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  213s] test_all is a Catch v2.13.10 host application.
[  213s] Run with -? for options
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 i/o operations
[  213s]   decimal output
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:432
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:444: FAILED:
[  213s]   REQUIRE( strstr.str() == a_y.y )
[  213s] with expansion:
[  213s]   "32915523077329923803837095652197137681"
[  213s]   ==
[  213s]   "177508241696884716594379275141355476411"
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 i/o operations
[  213s]   hex output
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:452
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:464: FAILED:
[  213s]   REQUIRE( strstr.str() == a_y.y )
[  213s] with expansion:
[  213s]   "18c34c954a2915bb858ad803aac7fd11"
[  213s]   ==
[  213s]   "858ad803aac7fd1118c34c954a2915bb"
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 i/o operations
[  213s]   octal output
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:472
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:484: FAILED:
[  213s]   REQUIRE( strstr.str() == a_y.y )
[  213s] with expansion:
[  213s]   "306064622522424425567026126600165261776421"
[  213s]   ==
[  213s]   "2054255400352543775042143032311251212212673"
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 i/o operations
[  213s]   decimal input
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:492
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:506: FAILED:
[  213s]   REQUIRE( u == a_y.y )
[  213s] with expansion:
[  213s]   177508241696884716594379275141355476411
[  213s]   ==
[  213s]   32915523077329923803837095652197137681
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 i/o operations
[  213s]   hex input
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:526
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:540: FAILED:
[  213s]   REQUIRE( u == a_y.y )
[  213s] with expansion:
[  213s]   177508241696884716594379275141355476411
[  213s]   ==
[  213s]   32915523077329923803837095652197137681
[  213s] 
[  213s] -------------------------------------------------------------------------------
[  213s] uint128 i/o operations
[  213s]   octal input
[  213s] -------------------------------------------------------------------------------
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:568
[  213s] ...............................................................................
[  213s] 
[  213s] /home/abuild/rpmbuild/BUILD/trng4-4.26/tests/test_uint128.cc:582: FAILED:
[  213s]   REQUIRE( u == a_y.y )
[  213s] with expansion:
[  213s]   177508241696884716594379275141355476411
[  213s]   ==
[  213s]   32915523077329923803837095652197137681
[  213s] 
[  213s] ===============================================================================
[  213s] test cases:  1 |  0 passed | 1 failed
[  213s] assertions: 40 | 34 passed | 6 failed
[  213s] 
[  213s] 
[  213s]  7/59 Test  #8: GF(2) .........................................   Passed    0.28 sec
[  213s]  8/59 Test  #9: integer math ..................................   Passed    0.28 sec
[  213s]       Start 14: special_functions - long double
[  213s]       Start 15: continuous distributions - float
[  213s]       Start 16: continuous distributions - double
[  213s]  9/59 Test  #7: basic matrix operations .......................   Passed    0.70 sec
[  213s] 10/59 Test #10: linear algebra ................................   Passed    0.56 sec
[  213s]       Start 17: continuous distributions - long double
[  213s]       Start 18: discrete distributions - float
[  213s] 11/59 Test #12: special_functions - float .....................   Passed    0.52 sec
[  213s]       Start 19: discrete distributions - double
[  213s] 12/59 Test #13: special_functions - double ....................   Passed    0.44 sec
[  213s]       Start 20: discrete distributions - long double
[  213s] 13/59 Test #11: modulo inverse ................................   Passed    0.57 sec
[  213s]       Start 21: engines - trng::lcg64
[  213s] 14/59 Test #14: special_functions - long double ...............   Passed    0.47 sec
[  213s]       Start 22: engines - trng::lcg64_shift
[  214s] 15/59 Test #18: discrete distributions - float ................   Passed    0.22 sec
[  214s]       Start 23: engines - trng::lcg64_count_shift
[  214s] 16/59 Test #20: discrete distributions - long double ..........   Passed    0.21 sec
[  214s]       Start 24: engines - trng::count128_lcg_shift
[  214s] 17/59 Test #19: discrete distributions - double ...............   Passed    0.34 sec
[  214s]       Start 25: engines - trng::mrg2
[  214s] 18/59 Test #15: continuous distributions - float ..............   Passed    0.57 sec
[  214s]       Start 26: engines - trng::mrg3
[  215s] 19/59 Test #21: engines - trng::lcg64 .........................   Passed    2.21 sec
[  215s]       Start 27: engines - trng::mrg3s
[  216s] 20/59 Test #23: engines - trng::lcg64_count_shift .............   Passed    2.24 sec
[  216s]       Start 28: engines - trng::mrg4
[  217s] 21/59 Test #22: engines - trng::lcg64_shift ...................   Passed    3.79 sec
[  217s]       Start 29: engines - trng::mrg5
[  218s] 22/59 Test #24: engines - trng::count128_lcg_shift ............   Passed    4.08 sec
[  218s]       Start 30: engines - trng::mrg5s
[  219s] 23/59 Test #16: continuous distributions - double .............   Passed    5.59 sec
[  219s]       Start 31: engines - trng::yarn2
[  223s] 24/59 Test #25: engines - trng::mrg2 ..........................   Passed    9.03 sec
[  223s]       Start 32: engines - trng::yarn3
[  225s] 25/59 Test #26: engines - trng::mrg3 ..........................   Passed   11.58 sec
[  225s]       Start 33: engines - trng::yarn3s
[  226s] 26/59 Test #27: engines - trng::mrg3s .........................   Passed   10.38 sec
[  226s]       Start 34: engines - trng::yarn4
[  226s] 27/59 Test #29: engines - trng::mrg5 ..........................   Passed    8.92 sec
[  226s]       Start 35: engines - trng::yarn5
[  226s] 28/59 Test #31: engines - trng::yarn2 .........................   Passed    7.65 sec
[  226s]       Start 36: engines - trng::yarn5s
[  230s] 29/59 Test #30: engines - trng::mrg5s .........................   Passed   12.84 sec
[  230s]       Start 37: engines - trng::lagfib2xor_521_64
[  231s] 30/59 Test #28: engines - trng::mrg4 ..........................   Passed   15.17 sec
[  231s]       Start 38: engines - trng::lagfib4xor_521_32
[  231s] 31/59 Test #32: engines - trng::yarn3 .........................   Passed    8.51 sec
[  231s]       Start 39: engines - trng::lagfib2plus_521_32
[  234s] 32/59 Test #37: engines - trng::lagfib2xor_521_64 .............   Passed    3.47 sec
[  234s]       Start 40: engines - trng::lagfib4plus_521_64
[  234s] 33/59 Test #39: engines - trng::lagfib2plus_521_32 ............   Passed    3.21 sec
[  235s]       Start 41: engines - trng::mt19937
[  235s] 34/59 Test #35: engines - trng::yarn5 .........................   Passed    8.72 sec
[  235s]       Start 42: engines - trng::mt19937_64
[  237s] 35/59 Test #36: engines - trng::yarn5s ........................   Passed   10.74 sec
[  237s]       Start 43: engines - trng::xoshiro256plus
[  237s] 36/59 Test #34: engines - trng::yarn4 .........................   Passed   11.43 sec
[  237s]       Start 44: parallel engines - trng::lcg64
[  238s] 37/59 Test #17: continuous distributions - long double ........   Passed   24.33 sec
[  238s]       Start 45: parallel engines - trng::lcg64_shift
[  238s] 38/59 Test #38: engines - trng::lagfib4xor_521_32 .............   Passed    6.66 sec
[  238s]       Start 46: parallel engines - trng::lcg64_count_shift
[  238s] 39/59 Test #44: parallel engines - trng::lcg64 ................   Passed    0.45 sec
[  238s]       Start 47: parallel engines - trng::count128_lcg_shift
[  238s] 40/59 Test #46: parallel engines - trng::lcg64_count_shift ....   Passed    0.40 sec
[  238s]       Start 48: parallel engines - trng::mrg2
[  238s] 41/59 Test #45: parallel engines - trng::lcg64_shift ..........   Passed    0.46 sec
[  238s]       Start 49: parallel engines - trng::mrg3
[  238s] 42/59 Test #47: parallel engines - trng::count128_lcg_shift ...   Passed    0.48 sec
[  238s]       Start 50: parallel engines - trng::mrg3s
[  238s] 43/59 Test #48: parallel engines - trng::mrg2 .................   Passed    0.37 sec
[  239s]       Start 51: parallel engines - trng::mrg4
[  239s] 44/59 Test #49: parallel engines - trng::mrg3 .................   Passed    0.45 sec
[  239s]       Start 52: parallel engines - trng::mrg5
[  239s] 45/59 Test #50: parallel engines - trng::mrg3s ................   Passed    0.46 sec
[  239s]       Start 53: parallel engines - trng::mrg5s
[  239s] 46/59 Test #52: parallel engines - trng::mrg5 .................   Passed    0.35 sec
[  239s]       Start 54: parallel engines - trng::yarn2
[  239s] 47/59 Test #51: parallel engines - trng::mrg4 .................   Passed    0.52 sec
[  239s]       Start 55: parallel engines - trng::yarn3
[  239s] 48/59 Test #53: parallel engines - trng::mrg5s ................   Passed    0.54 sec
[  239s]       Start 56: parallel engines - trng::yarn3s
[  239s] 49/59 Test #40: engines - trng::lagfib4plus_521_64 ............   Passed    5.41 sec
[  239s] 50/59 Test #55: parallel engines - trng::yarn3 ................   Passed    0.36 sec
[  239s]       Start 57: parallel engines - trng::yarn4
[  239s]       Start 58: parallel engines - trng::yarn5
[  239s] 51/59 Test #54: parallel engines - trng::yarn2 ................   Passed    0.42 sec
[  239s]       Start 59: parallel engines - trng::yarn5s
[  240s] 52/59 Test #56: parallel engines - trng::yarn3s ...............   Passed    0.39 sec
[  240s] 53/59 Test #57: parallel engines - trng::yarn4 ................   Passed    0.53 sec
[  240s] 54/59 Test #58: parallel engines - trng::yarn5 ................   Passed    0.53 sec
[  240s] 55/59 Test #59: parallel engines - trng::yarn5s ...............   Passed    0.51 sec
[  242s] 56/59 Test #33: engines - trng::yarn3s ........................   Passed   16.35 sec
[  243s] 57/59 Test #43: engines - trng::xoshiro256plus ................   Passed    5.14 sec
[  248s] 58/59 Test #41: engines - trng::mt19937 .......................   Passed   13.70 sec
[  252s] 59/59 Test #42: engines - trng::mt19937_64 ....................   Passed   17.10 sec
[  252s] 
[  252s] 95% tests passed, 3 tests failed out of 59
[  252s] 
[  252s] Total Test time (real) =  39.82 sec
[  252s] 
[  252s] The following tests FAILED:
[  252s] 	  2 - uint128 math (Failed)
[  252s] 	  4 - uint128 bitwise shift operators (Failed)
[  252s] 	  5 - uint128 i/o operations (Failed)
[  252s] Errors while running CTest
```
</details>

You can find the latest full build log at
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:zSystems/trng/standard/s390x

The build and tests of 4.25 succeeded.

This is probably related to #32, but note that s390x shows different wrong values than aarch64. For example, the i/o operation failures on aarch64 fail `with expansion: "<big number>" == "0"`, while the failures on s390x say `with expansion: "<big number>" == "<another big number>"`, where `another big number` often is `32915523077329923803837095652197137681` (decimal)

**Comment by rabauke** [comment] 2024-08-25 12:53
@cboltz Thanks for this report. Issues will be fixed in the next release.  Though, I will work on #32 first.  Possibly, I will ask for further information in the future because I do not have access to s390x hardware.

**Comment by cboltz** [comment] 2024-08-25 14:14
Access to s390x hardware is a solvable problem ;-)

You can get access to a s390x VM for 120 days in the LinuxOne Community Cloud: https://linuxone.cloud.marist.edu/ (and after it expires, you can register again to get a new VM for another 120 days).

There's also an option for open source projects to get a VM permanently - I can provide more details if you are interested.

**Comment by rabauke** [comment] 2024-09-02 12:18
@cboltz Thanks, for drawing my attention to the LinuxOne Community Cloud.

**Comment by rabauke** [comment] 2024-09-02 13:53
@cboltz I understand (from the provided log file)

```
[    0s] Using BUILD_ARCH=s390x:s390
```

that the code is compiled on a 64-bit hardware (s390x) for a 32-bit ABI (s390).  Is this understanding correct?

**Comment by rabauke** [comment] 2024-09-02 20:43
@cboltz I am still unable to reproduce the issue. Though, I think I am able to understand the root cause from investigating the provided log files. Can you please check if the issue still occurs for the latest version from git master (which contains two fixes)?

**Comment by cboltz** [comment] 2024-09-03 14:21
> @cboltz I understand (from the provided log file)
> 
> ```
> [    0s] Using BUILD_ARCH=s390x:s390
> ```
> 
> that the code is compiled on a 64-bit hardware (s390x) for a 32-bit ABI (s390). Is this understanding correct?

That line is indeed a bit confusiong.

However, I'd be very surprised if it would be built for 32-bit - and if you look down a few lines, you'll see

`[    1s] Building trng for project 'home:badshah400:branches:devel:libraries:c_c++' repository 'openSUSE_Factory_zSystems' arch 's390x' srcmd5 '5432507ecec9d3dece53ac898f9b4e91'`

Also, the build log, commands etc. all contain s390x which means it's built for 64 bit s390x.


> @cboltz I am still unable to reproduce the issue. Though, I think I am able to understand the root cause from investigating the provided log files. Can you please check if the issue still occurs for the latest version from git master (which contains two fixes)?

Luckily Atri did the testing for #32 on https://build.opensuse.org/package/show/home:badshah400:branches:devel:libraries:c_c++/trng *) so I could just check the result there.

Good news - the patch also fixes the build for s390x :-)

*) Note that this link has a limited lifetime - the branch project will probably vanish once it's submitted towards the devel project.

**Comment by rabauke** [comment] 2024-09-04 18:08
@cboltz Thanks for testing and feedback. I will prepare a new release soon.

**Closed by rabauke** 2024-09-04 18:08 UTC
Labels: bug, unit tests
